export const btnRegister = ["RO'YXATDAN O'TISH", "ЗАРЕГИСТРИРОВАТЬСЯ"];
export const btnAvtor = ["Do'smuratov G'olib", "Голиб Дycмypamoв"];
export const endDate = [
  "2 OY",
  "2 месяца",
  "kurs davomiyligi",
  "Длительность курса",
];
export const countStudents = [
  "30 TA",
  "30",
  "kursdagi joylar soni",
  "мест на курсе",
];
export const title = [
  "Restoran biznesini qurishdagi barcha bilimlar",
  "Bce o ресторанном бизнесе",
  "O'z-o'zini boshqaruvchi restoran qanday yaratiladi",
  "Или как создать самоуправляемый ресторан",
];
export const expeirensec = [
  "yillik Restorator",
  "лет Ресторатор",
  "yillik IT tadbirkor",
  "лет IT-предприниматель",
];

export const digitstext = [
  [
    "O'z restorani, kafe, oshxona, fastfudini ochmoqchi bo'lgan har bir kishi",
    "Всем, кто хочет открыть свой ресторан (кафе, столовую, фастфуд)",
  ],
  [
    "Hozirda restorani bor, lekin uni masshtablashtirishni xohlaydigan har bir kishi",
    "Всем, кто хочет получать удовольствие от ресторанного бизнеса",
  ],
  [
    "Tarmoqqa ega bo'lgan, lekin o'zi uchun yetarli vaqt ajrata olmayotgan biznes egasi uchun",
    "Всем, y кого уже есть ресторан и он хочет второй",
  ],
  [
    "Allaqachon o'z restoraniga ega, lekin biznesini tizimlashtirishni va operatsion boshqaruvda kamroq vaqt o'tkazmoqchi bo'lgan har bir kishi",
    "Всем, y кого уже есть свой ресторан, но он хочет систематизировать свой бизнес и меньше времени проводить в операционке",
  ],
  [
    "Restoran biznesidan zavq olishni istaganlar uchun",
    "Всем, y кого уже есть сеть, но не хватает времени на себя",
  ],
];

export const resultText = [
  [
    "https://thumb.tildacdn.com/tild3266-3031-4733-b532-396133646262/-/cover/280x264/center/center/-/format/webp/6cebf751-69c4-4208-9.png",
    "Qanday qilib muvaffaqiyatli restoran yaratishni o'rganasiz",
    "Узнаете, как создавать успешные ресторанные концепции ",
  ],
  [
    "https://thumb.tildacdn.com/tild6335-3430-4565-a339-376537383033/-/cover/280x272/center/center/-/format/webp/d8067773-f518-4062-a.png",
    "Moliyani tushunishni boshlaysiz va pulning qayerdaligini bilib olasiz",
    "Начнете понимать финансы и поймете, где деньги лежат",
  ],
  [
    "https://thumb.tildacdn.com/tild3932-3665-4039-b837-313438343462/-/cover/280x280/center/center/-/format/webp/944e6dc3-37ac-453e-a.png",
    "Restoraningizga mijozlarni jalb qiluvchi vositalarga ega bo'lasiz",
    "Получите инструменты для привлечение клиентов в ваш ресторан",
  ],
  [
    "https://thumb.tildacdn.com/tild3665-6562-4663-b764-366565666532/-/cover/280x262/center/center/-/format/webp/0e461389-171f-4fb7-8.png",
    "Smart restoran tizimini qanday yaratishni bilib olasiz ",
    "Научитесь создавать систему умного ресторана",
  ],
  [
    "https://thumb.tildacdn.com/tild3530-3838-4333-b935-303361636462/-/cover/268x270/center/center/-/format/webp/fe84a9ac-66a1-4197-b.png",
    "Xodimlaringiz biznesingiz farovonligi haqida o'ylashni boshlashadi",
    "Ваши сотрудники начнут думать o процветании вашего бизнеса",
  ],
];

export const moduleUzb = [
  [
    "Konsepsiya",
    "",
    [
      "Restoran konsepsiyasi nima?",
      "Qanday qilib muvaffaqiyatli kontseptsiyani yaratish mumkin?",
      " Muvaffaqiyatli konsepsiyalarga misollar",
      "Missiya nima?",
      "O'z muassasangizning missiyasini qanday shakllantirish kerak?",
      "Bozor tahlilini qanday o'tkazish kerak?",
      "Maqsadli auditoriyangizni qanday aniqlash mumkin?",
      "Uni qanday qilib to'g'ri segmentatsiya qilish kerak?",
      "Restorangizni maqsadli auditoriyangizga moslashtirib qurish",
    ],
    "Biz siz bilan konsepsiya yaratishni amalda qo'llaymiz. Bu jarayonda siz missiya haqida hamma narsani bilib olasiz va amalda o'z missiyangizni yaratasiz va yana ko'p narsalarni bilib olasiz.",
  ],
  [
    "Marketing. Aloqa nuqtasi",
    "",
    [
      "Marketing nimadan boshlanadi?",
      "Aloqa nuqtalari nima va ular qanday boladi?",
      "Ular orqali mehmonga qanday qilib to'g'ri munosabatda bo'lish",
      "Ularni tahlil qilish",
      "Marketing kommunikatsiyalari haqida",
      "Restoranni to'g'ri PR qilish haqida",
      "Reklama instrumentlari haqida",
      "Sodiqlik tizimi, uning turlari va ulardan samarali foydalanish haqida",
      "Brend yaratish va marketingga doir ko'plab bilimlar beriladi",
    ],
    "Sizlar bilan birgalikda mavjud restoranlar uchun aloqa nuqtalarini yaxshilash va kuchli marketing quramiz.",
  ],
  [
    "Loyihani yaratish - Restoranga asos solish",
    "",
    [
      "Qanday qilib to'g'ri joylashuvni tanlash mumkin?",
      "To'g'ri Ijara shartnomasini imzolash usullari",
      "Investitsiya jalb qilish",
      "Investor va sheriklar bilan kelishuv imzolash qoidalari",
      "Qanday loyiha turlari mavjud va ularni qurish mumkin",
      "To'g'ri mebellarni tanlash va ularning zaldagi to'g'ri joylashuvini ishlab chiqish",
      "Loyihaga mos bo'lgan barcha restoran texnikalarini nimasiga qarab tanlash kerakligi va texnikalar haqida bilishingiz kerak bo'lgan barcha ma'lumotlar",
      "O'z loyihangiz uchun eng mos bo'lgan idish-tovoqlarni tanlash",
      "Havo aylanish, isitish va sovutish tizimlari haqida",
      "Restoranni avtomatlashtirish haqida",
      "To'g'ri ovoz, yorug'lik va muassasada yqoimli atmosferani yaratadigan barcha narsalar haqida",
      "Siz restoraningizni yuqoridagi barcha narsalar bilan to'ldirishni ",
      "o'rganasiz va restoraningizni yaratishni boshlaysiz",
      "Siz restoran atmosferasi va uni tashkil etuvchi barcha narsalar haqida bilib olasiz",
    ],
    "",
  ],
  [
    "Loyihamiz uchun yetkazib beruvchilarni tanlash",
    "",
    [
      "Qanday qilib eng munosib yetkazib beruvchini tanlash",
      "Yetkazib beruvchi bilan to'g'ri muzokara olib borish",
      "O'zingiz uchun eksklyuziv shartlarni muhokama qilish usullari",
      "Qanday qilib ular bilan o'zaro hisob-kitoblarni kelishish va yuritish",
      "Qanday qilib yetkazib beruvchining narxlarini nazorat saqlash",
      "Qanday qilib yetkazib beruvchilar orasida tender uyushtirish",
      "Kim etkazib beruvchilarga buyurtma berishi kerak",
      "Qanday qilib tovarlar qabul qilinadi va schyot-fakturalar beriladi",
      "Qanday qilib hujjatlashtirish ishlari yuritiladi",
      "Avtomatik buyurtma modulidan qanday foydalanish kerak",
      "Shu kuni biz yirik B2B yetkazib beruvchilardan birining ofisiga tashrif buyuramiz va siz hammasini amalda sinab ko'rish imkoningiz bo'ladi",
    ],
    "Shu kuni biz yirik B2B yetkazib beruvchilardan birining ofisiga tashrif buyuramiz va siz hammasini amalda sinab ko'rish imkoningiz bo'ladi",
  ],
  [
    "Menyuni rejalashtirish",
    "",
    [
      "Kontseptsiyangiz uchun to'g'ri menyuni qanday tanlash mumkin",
      "Menyu qanday atributlarga ega bo'lishi kerak?",
      "Menyular qanday bo'ladi?",
      "Menyudagi taomlarning optimal soni qancha bo'lishi kerak",
      "Ovqatlar qanday taqdim qilinishi kerak",
      "Qanaqa mashhur yo'nalishlar mavjud",
      "Yaqin davr ichida qanaqa trendlar bo'lishi kutilmoqda",
      "Menyuga qanday qilib storytelling kiritish yo'llari",
      "Degustatsiya to'plami nima?",
      "Menyu dizayni qanday bo'lishi kerak?",
      "Nonushta menyusi va tushlik menyusi nima va u asosiy menyudan qanday farq qiladi",
      "Banket menyusi nima?",
      "Menyuda o'ziga xosliklar yaratish haqida",
      "Menyu yaratishdagi xatolar",
      "Menyudagi taomlarni to'g'ri narxlash",
    ],
    "Va restoranda menyu tuzish haqida ko'plab bilimlar. Shu kuni siz o'zingizning menyuingizni tuzish bilan tajriba o'tkazasiz.",
  ],
  [
    "HR - Xodimlar",
    "",
    [
      "Nomzod portretini ishlab chiqish",
      "Qanday qilib to'g'ri e'lon berish kerak?",
      "Xodimlarni suhbat asosida qabul qilish jarayonini to'g'ri shakllantirish",
      "Qanday qilib Nomzodlarni sinovdan o'tkazish kerak",
      "Qanday turdagi xodimlar bo'ladi",
      "Qadriyatlar nima?",
      "Xodimlarga qanday qilib to'g'ri ta'lim beriladi?",
      "Mas'uliyatlarni to'g'ri belgilash",
      "Muntazam baholashni qanday o'tkazish kerak",
      "Xodimlar qanday qilib baholanadi?",
      "Standartlar va prinsiplar haqida",
      "Reglament va biznes jarayoni nima va uni qanday tuzish kerak",
      "Qanday qilib va nima uchun ishdan bo'shatish kerak",
    ],
    "",
  ],
  [
    "Liderlik",
    "",
    [
      "Lider o'zi kim?",
      "Norasmiy liderni qanday aniqlash mumkin",
      "Norasmiy rahbarlar qanday tahdidlarni keltirib chiqarishi mumkin",
      "Qanday qilib o'z jamoangiz uchun Liderga aylanish mumkin",
      "Korporativ madaniyat nima va uni qanday yaratish kerak",
      "Qadriyatlar nima va ularni qanday aniqlash mumkin",
      "Rituallar nima?",
      "Kompaniya nizomi nima va uni qanday yozish kerak",
      "“Эмоциональный банковский счет” nima?",
      "Qanday qilib to'g'ri vakolat berish kerak",
      "O'yin standartlari va qoidalari qanday?",
    ],
    "Siz o'zingizni lider sifatida sinab ko'rishingiz va jamoani boshqarishning amaliy kursidan o'tishingiz mumkin",
  ],
  [
    "Menejment",
    "",
    [
      "O'z o'zini rivojlantiruvchi restoran tizimini qurish prinsiplari haqida",
      "Qanday qilib hamma xodimlar o'z mehnatining natijasiga mos maosh oluvchi boshqaruv tizimini qurish mumkin",
      "Qanday qilib biznesingizni alohida daromad markazlariga bo'lish mumkin",
      "Qanday qilib oshxonani tsex'larga bo'lish va ularni mustaqil biznes shakliga o'tkazish mumkin",
      "Qanday qilib zalni zonalarga bo'lish va zonalarga mas'ullarni belgilash kerak",
      "Qanday qilib ofitsiantlarni Alfa va Beta guruhlarga ajratib, ularning samaradorligini 2 barobarga oshirish mumkin",
      "Har bir mas'ullarning roli va topshiriqlarini ishlab chiqish orqali ularning samaradorligini to'g'ri baholash haqida",
      "Qanday qilib hamma xodimlarni sizning restoraningiz rivojlanishi uchun harakat qilishlarini ta'minlash mumkin?",
      "Boshqaruvchining vazifalari qanday?",
      "Qanday qilib to'g'ri boshqaruvchini tanlash va uni to'g'ri baholash kerak?",
    ],
    "Siz bu dars davomida turli xil pozitsiyalarni eksperiment qilish bilan tajriba o'tkazishga va tizimimizning tamoyillarini tushunib olasiz",
  ],
  [
    "Menejment-2",
    "",

    [
      "Qanday qilib to'g'ri topshiriq berish kerak",
      "To'g'ri jamoaviy yig'ilishlar o'tkazish haqida",
      "RNP nima?",
      "Qaror qabul qilish matritsasi nima va undan qanday foydalanish kerak",
      "Stratessiyalar nima va ularni qanday o'tkazish kerak",
      "Toplarni qanday boshqarish kerak",
      "Matritsa tuzilishi nima?",
    ],
    "Biz siz bilan bu kunda strategik sessiyalar o'tkazamiz. Bu jarayonda barcha ishtirokchilarga turli rollar beriladi va bu orqali siz eshitishni va o'z fikrlaringizni hamkasblaringizni to'g'ri yetkazib berishni o'rganasiz.",
  ],
  [
    "Servis",
    "",
    [
      "Mehmonlarning qo'rquvi va ularni qanday bartaraf etish kerakligi haqida",
      "Empatiya va uni qanday rivojlantirish haqida",
      "Stol bron qilish va uni avtomatlashtirish uchun IT vositalaridan foydalanish haqida",
      "Mehmonni kutib olish va ijobiy munosabatni yaratish haqida",
      "WOW effekt yaratish haqida",
      "Mehmonlarning restoranga tashrif buyurish maqsadlari haqida",
      "Hissiy xizmat va uni qanday qurish haqida",
      "Xizmat ko'rsatishdagi o'ziga xosliklar haqida",
      "Xizmat ko'rsatishda mobil telefonlardan foydalanish haqida",
      "Buyurtma qabul qilishda QR Menyuning ahamiyati haqida",
      "WOW effekti va unga qanday erishish mumkinligi haqida",
      "Mijozlar fikr-mulohazalarni qanday qabul qilish va nima uchun bu juda muhim ekani haqida",
      "Skriptlar nima va ularni qanday yozish haqida",
      "Xizmat ko'rsatish markazi, parkovka va boshqa ko'plab boshqa mavzular haqida",
    ],
    "Biz xizmatni baholash bo'yicha amaliy topshiriqlar va uni takomillashtirish bo'yicha tavsiyalar beramiz",
  ],
  [
    "Moliya",
    "",
    [
      "Restoranda qanday moliyaviy hisobot turlari qo'llaniladi",
      "CHOK nima?",
      "P&L nima?",
      "Cash Flow nima?",
      "ABC tahlili nima va undan qanday foydalanish kerak",
      "XYZ tahlili nima?",
      "Debitorlik va kreditorlik qarzlarini qanday boshqarish kerak",
      "Telefoningiz orqali biznesingizni qanday boshqarish kerak",
      "Kalkulyatsion va texnologik kartalar qanday farq qiladi",
      "Ularni qanday tuzish kerak",
    ],
    "Ushbu darsdan keyin siz o'zingiz mustaqil ravishda xarajatlarni va texkartalarni o'zingiz o'tkazishni va ularni tizimlarga kiritishni boshlaysiz. Siz xarajatlar bilan ishlashni va uni tahlil qilishni o'rganasiz.",
  ],
  [
    "Moliya - 2",
    "",
    [
      "Inventarizatsiyani qanday o'tkazish kerak",
      "Inventarizatsiya nomuvofiqligining sabablari nimada",
      "Restoranda tovar hisobini qanday qo'yish kerak",
      "Avtomatik buyurtma tizimini qanday sozlash kerak",
      "Schyot-fakturalarni hisobga olishni qanday tashkil qilish kerak",
      "Biz foydalanadigan asosiy biznes ko'rsatkichlari qanday",
      "Kassa intizomi nima va uni qanday o'rnatish kerak",
      "Fiskal onlayn kassa bilan qanday ishlash kerak",
      "Byudjetlashtirish nima va uni qanday amalga oshirish kerak",
      "Inventarizatsiya va past baholarni qanday saqlash kerak",
      "Amortizatsiyani qanday saqlash kerak",
    ],
    "Shu kuni siz o'zingiz inventarizatsiya qilasiz va uning natijalarini tahlil qilasiz",
  ],
  [
    "O'g'rilik",
    "",
    [
      "Sizni qanday o'g'irlashayotganini o'rganasiz",
      "Zakup",
      "Oshpaz",
      "Ofitsiant",
      "Barmen",
      "Kassir",
      "Xostes",
      "Qo'riqchi",
      "Tozalik xodimlari",
      "Buxgalter",
    ],
    "Va yana ko'p narsalar. Siz o'g'irlik nimaga olib kelishini va u bilan qanday kurashishni bilib olasiz.",
  ],
  [
    "CRM",
    "",
    [
      "Samarali SMM siyosatini qanday qurish kerak",
      "Reklama orqali mijozlarni qanday jalb qilish kerak",
      "Tone of Voice nima?",
      "Bloger influenserlar bilan qanday ishash kerak",
      "Partizan marketingi nima",
      "Qanday qilib mehmonlaringizni promouterlaringizga aylantirish mumkin",
      "Sodiqlik tizimi bilan ishlash haqida",
      "RFM matritsasi nima",
      "Restoran brendi ustida qanday ishlash kerak",
      "Shaxsiy brend ustida qanday ishlash kerak",
      "Mashhur brendlar bilan hamkorlikni qanday tashkil qilish kerak",
      "Mijozlar bazasini qanday tahlil qilish kerak",
      "Mijozlar bazasidan qanday samarali foydalanish kerak",
      "Foyda formulasi yordamida foydani qanday oshirish mumkin",
    ],
    "",
  ],
  [
    "Xavfsizlik. Oziq-ovqat xavfsizligi",
    "",
    [
      "Oziq-ovqat xavfsizligi nima?",
      "Tozalik standartlari haqida",
      "Oziq-ovqat mahsulotlarini saqlash standartlari haqida",
      "Pishirish standartlari haqida",
      "Kimyoviy xavflar haqida",
      "Mikrobiologik xavf haqida",
      "Jismoniy xavf haqida",
      "XASSP nima ekani haqida",
      "Tekshirish organlari oldidagi xavfsizlik to'g'risida",
      "Yong'in xavfsizligi to'g'risida",
    ],
    "Sizning biznesingizdagi ko'plab muammolardan o'zingizni himoya qilishga yordam beradigan yana ko'plab narsalar haqida",
  ],
  [
    "Yetkazib berish (Доставка)",
    "",
    [
      "Yetkazib berish turlari haqida",
      "Darkstorlar haqida",
      "Agregatorlar haqida",
      "Biznesning o'zini yetkazib berish tizimi haqida",
      "Call-center tuzish haqida",
      "MA ni aniqlash va unga ta'sir qilish usullari to'g'risida",
      "Yetkazib berish reklamasi haqida",
      "Logistika tamoyillari haqida",
      "Yetkazib berish zonalarini qurish haqida",
      "Yetkazib berishni tashkil qilish uchun IT tizimi haqida",
      "Sayt va Telegram etkazib berish botini sozlash haqida",
      "Yetkazib berishda online to'lovlar haqida",
      "Yetkazib berish standartlari haqida",
      "Yetkazib berish xizmatini tashkil qilishda tez-tez uchraydigan xatolar haqida",
      "Samaradorlikni baholashning asosiy ko'rsatkichlari haqida",
    ],
    "Natijada siz o'zingizning yetkazib berish xizmatingizni sozlashingiz va uning ko'rsatkichlarini ro'yxatdan o'tkazishingiz mumkin.",
  ],
];

export const moduleRus = [
  [
    "Концепция",
    "B первый день вы узнаете:",
    [
      "Что такое концепция ресторана",
      "Как создать успешную концепцию",
      "Познакомитесь с примерами успешных концепций",
      "Что такое миссия",
      "Как сформировать миссию своего заведения",
      "Как проводить анализ рынка",
      "Как определять свою целевую аудиторию",
      "Как правильно ее сегментировать",
      "Как настроить свой ресторан на свою целевую аудиторию",
    ],
    "Мы с вами будем экспериментировать с созданием концепции. Вы узнаете все о миссии и попробуете на практике создать свою миссию и еще многое другое.",
  ],
  [
    "Маркетинг. Точки контакта",
    "Второй день нашего курса посвящен ресторанному маркетингу. Сегодня вы узнаете:",
    [
      "С чего начинается маркетинг",
      "Что такое точки контакта и какие они бывают",
      "Как через них правильно воздействовать на гостя",
      "Как их ",
      "О маркетинговых коммуникациях",
      "О ресторанном PR",
      "О инструментах рекламы",
      "О системах лояльности, их видах и их эффективном использовании",
      "О создании бренда и еще многом другом, касательно маркетинга.",
    ],
    "Вместе с вами мы будем строить маркетинг и улучшать точки контакта на существующих ресторанах.",
  ],
  [
    "Создание проекта",
    "В этот день каждый из вас будет создавать свой ресторан в проекте. Вы узнаете:",
    [
      "Как выбрать правильное расположение",
      "Как решать вопросы с арендой",
      "Привлечением инвестиций",
      "Как договариваться с партнерами и инвесторами",
      "Какие бывают проекты и как их заказывать",
      "Как выбрать правильную мебель и расположить ее в зале",
      "Все о ресторанном оборудовании, о его особенностях и научитесь его подбирать под проект",
      "Опосуде и инвентаре и с нами вместе вы подберете оптимальную посуду для своего проекта",
      "О вентиляции, отоплении и кондиционировании",
      "Об автоматизации ресторана",
      "О правильном звуке, освещении и обо всем, что создает атмосферу в заведении",
      "Вы научитесь наполнять свой ресторан всем вышеуказанным мы с вами начнем создавать",
      "Вы узнаете о ресторанной атмосфере и об всем, что ее формирует",
    ],
    "",
  ],
  [
    "Выбор поставщиков для нашего проекта",
    "Мы с вами будем подбирать поставщиков для нашего проекта. Вы узнаете,",
    [
      "Как подобрать оптимального поставщика",
      "Как правильно вести переговоры с поставщиком",
      "Как договариваться об эксклюзивных для себя условиях",
      "Как вести с ними взаиморасчеты",
      "Как мониторить цены поставщиков",
      "Как устраивать тендеры между поставщиками",
      "Кто должен делать заказы поставщикам",
      "Как принимаются товары и оформляются накладные",
      "Как ведется документация",
      "Как использовать модуль автозаказа",
    ],
    "В это день мы с вами посетим крупного В2В поставщика и вы на практике можете все это опробовать",
  ],
  [
    "Меню",
    "5й день нашего курса посвящен составлению меню. В этот день вы узнаете:",
    [
      "Как выбрать правильное меню для вашей концепции",
      "Какими атрибутами должно обладать меню",
      "Какие меню бывают",
      "Какое должно быть оптимально количество блюд в меню",
      "Как должны подаваться блюда",
      "Какие существуют популярные направления",
      "Какие треды ожидаются в ближайшее время",
      "Как включить сторитейлинг в ваше меню",
      "Что такое дегустационный сет",
      "Каким должен быть дизайн меню",
      "Что такое Меню для завтраков и обеденное меню и чем оно отличается от основного",
      "Что такое банкетное меню",
      "Какие могут быть Фишки в меню",
      "Какие бывают ошибки при составлении меню",
      "Ценообразование в меню",
    ],
    "И еще многое о составлении меню в ресторане. В это день вы можете поэкспереметировать с составлением своего меню",
  ],
  [
    "HR",
    "Этот день посвящен вашему самому ценному ресурсу - человеческому капиталу. Вы узнаете:",
    [
      "Как составить портрет кандидата",
      "Как давать правильное объявление",
      "Как проводить собеседования",
      "Как тестировать кандидатов",
      "Какие типы сотрудников бывают",
      "Что такое ценности",
      "Как правильно обучать сотрудников",
      "Как вводить должность",
      "Как проводить регулярные аттестации",
      "Как оценивать сотрудников",
      "О принципах и стандартах",
      "Что такое регламент и бизнес процесс и как его составлять",
      "Как и за что увольнять",
    ],
    "",
  ],
  [
    "Лидерство",
    "Здесь мы будем говорить о лидерстве. О том, чем лидерство отличается от менеджмента. Вы узнаете:",
    [
      "Кто такой лидер",
      "Как выявить неформального лидера",
      "Какие угрозы могут представлять неформальные лидеры",
      "Как стать лидером для своей команды",
      "Что такое корпоративная культура и как ее сформировать",
      "Что такое ценности и как их выявить",
      "Что такое ритуалы",
      "Что такое конституция компании и как ее составить",
      "Что такое эмоциональный банковский счет",
      "Как правильно делегировать",
      "Что такое стандарты и правила игры",
    ],
    "Вы сможете попробовать себя в роли лидера и пройдете практический курс управления командой",
  ],
  [
    "Менеджмент",
    "В это день мы расскажем о менеджменте, об оргструктуте, их значении для компании. Вы узнаете о том:",
    [
      "О принципах построения системы саморазвивающегося ресторана",
      "Как построить правильную оргструктуру, в которой каждый будет получить за результат своего труда",
      "Как разделить ваше предприятие на отдельные центры прибыли",
      "Как разделить кухню на цеха и сделать их самостоятельными бизнесами",
      "Как зал разделить на зоны и как выбрать владельцев зон",
      "Как разделить официантов на Альфа и Бетта и увеличить их эффективность в 2 раза",
      "О ролях и задачах каждой должности и о том, как ее оценивать",
      "Как сделать всех заинтересованными в процветании вашего ресторана",
      "Что должен делать управляющий",
      "Как выбрать правильного управляющего и как его оценивать",
    ],
    "Вы попробуете поэксперементровать с оцинковкой различных должностей и поймете принципы нашей системы.",
  ],
  [
    "Продолжение темы менеджмента. В это день узнаете:",
    "",
    [
      "Как правильно делегировать",
      "Как правильно проводить совещания",
      "Что такое РНП",
      "Что такое Матрица решений и как ею пользоваться",
      "Что такое стратсессии и как их проводить",
      "Как управлять топами",
      "Что такое матричная структура",
    ],
    "Мы с вами будем в это день проводить стратегическую сессию, где вы научитесь работать в разных шляпах-ролях, научитесь слышать, слышать, а так же доносить свою мысль до других участников.",
  ],
  [
    "Сервис",
    "В этот день мы поговорим о сервисе, о его этапах, о правилах гостеприимства и их видах. Мы расскажем о комплиментах и о том, как их правило делать. А еще ты узнаешь:",
    [
      "О страхах гостей и о том, как их преодолеть",
      "Об эмпатии и о том, как ее развить",
      "О бронировании столов и использовании IT инструментов для ее автоматизации",
      "О встрече гостя и создании благоприятного настроя",
      "О создании эффекта ВАУ",
      "О целях посещения ресторана гостем",
      "О эмоциональном сервисе и способах его построения",
      "О фишках в обслуживании",
      "Об использовании мобильных телефонов в обслуживании",
      "Об QR меню при принятии заказа",
      "О Вау эффекте и о том, как его добиться",
      "О том, как брать обратную связь и о том, почему это так важно",
      "О том, что такое скрипты и как их писать",
      "О дом сервисах, парковке и еще многом другом",
    ],
    "Мы проведем практические задания по оценке сервиса и рекомендаций по его улучшению",
  ],
  [
    "Финансы",
    "В это день мы поговорим о построении финансовой системы в ресторане. Вы узнаете:",
    [
      "Какие виды финансовых отчетов используются в ресторане",
      "Что такое ЧОК",
      "Что такое P&L",
      "Что такое Cash Flow",
      "Что такое АВС анализ и как его использовать",
      "Что такое XYZ анализ",
      "Как управлять дебиторской и кредиторской задолженностью",
      "Как контролировать свой бизнес через свой телефон",
      "Чем отличаются калькуляционные и технологические карты",
      "Как их составлять",
    ],
    "Вы попробуете самостоятельно снять калькуляции и техкарты и внести их в системы. Вы научитесь работать с себестоимостью и анализировать ее.",
  ],
  [
    "Финансы - 2",
    "Мы продолжим с вами говорить о финансовой системе и в это день вы узнаете:",
    [
      "Как проводить инвентаризацию",
      "Какие причины несоответствия инвентаризации Как поставить товарный учет в ресторане",
      "Как настроить систему автоазказа",
      "Как наладить учет накладных",
      "Какие ключевые показатели бизнеса мы используем",
      "Что такое кассовая дисциплина и как ее наладить",
      "Как работать с Фискальной Онлайн кассой",
      "Что такое бюджетирование и как его проводить",
      "Как вести учет инвентаря и малоценки",
      "Как вести амортизацию",
    ],
    "В этот день вы самостоятельно проведете инвентаризацию и проведете анализ ее результатов",
  ],
  [
    "Как воруют",
    "Этот день полностью посвящен теме воровства в ресторане. Вы узнаете, как воруют:",
    [
      "Закупщик",
      "Повар",
      "Официант",
      "Бармен",
      "Кассир",
      "Хостес",
      "Охрана",
      "Уборщицы",
      "Бухгалтер",
    ],
    "И еще многие. Вы узнаете, к чему приводит воровство и как с этим бороться.",
  ],
  [
    "CRM",
    "Это день посвящен работе с клиентами. Вы узнаете:",
    [
      "Как построить эффективную SMM политику",
      "Как вилять на клиентов через рекламу",
      "Что такое Tone of Voice",
      "Как работать с блогерами и инфлюенсерами",
      "Что такое партизанский маркетинг",
      "Как сделать ваших гостей вашими промоутерами",
      "О работе с системой лояльности",
      "Что такое RFM матрица",
      "Как работать над брендом ресторана",
      "Как работать над личным брендом",
      "Как устроить коллаборацию с известными брендами",
      "Как анализировать свою клиентскую базу",
      "Как эффективно использовать свою клиентскую базу",
      "Как увеличить прибыль с помощью формули прибыли",
    ],
    "",
  ],
  [
    "Безопасность. Пищевая бесопасность",
    "В это день у нас посвящен безопасности. Вы узнаете:",
    [
      "Что такое пищевая безопасность",
      "О Стандартах чистоты",
      "О стандартах хранения продуктов",
      "О стандартах приготовления",
      "О Химической опасности",
      "О Микробилогической опасности",
      "О Физической опасности",
      "О том, что такое ХАССП",
      "О безопасности перед проверяющими органами",
      "О подранной безопасности",
    ],
    "И еще о многом другом, что поможет вам уберечься от многих проблем в вашем бизнесе.",
  ],
  [
    "Доставка",
    "И наконец мы поговорим о Доставке. Вы узнаете:",
    [
      "О видах доставки",
      "О дарксторах",
      "О агрегаторах",
      "О собственной доставке",
      "Об организации кол центра",
      "О выявлении ЦА и методах воздействия на него",
      "О рекламе в доставке",
      "О принципах логистики",
      "О выстраивании зон доставки",
      "Об IT системе для организации доставки",
      "О настройке сайта и телеграм бота доствки",
      "Об онлайн платежах в доставке",
      "О стандартах доставки",
      "О частых ошибках при организации службы доставки",
      "О ключевых метриках по оценке эффективности",
    ],
    "По итогам вы сможете настроить свою собственную службу доставки и прописать ее метрики.",
  ],
];
